#!/usr/bin/env python3
"""
galaxy_places.py — the shared placement layer for the feed fleet.

Every wire in the fleet answers the same question about a story: where is this
happening. Until now each one answered it alone, from its own short country
table, and only when the headline literally spelled a country's name. That put
between 1 and 46 per cent of most wires on the map and left the rest in a
counter marked "unplaced".

This resolves a story in five passes, stopping at the first that answers:

  1  a settlement named in the text            Kharkiv, Kaohsiung, Cuiabá
  2  a first-level division                    Bavaria, Kerala, Xinjiang, Ohio
  3  a country, by name or by demonym          Nigeria, Nigerian, Nigeria's
  4  an institution that belongs to one         EFSA, Ofcom, ANVISA, PMDA
  5  the country the source itself reports from

Pass 5 is the one that changes the numbers, and it is the weakest claim, so it
is marked: a point placed that way carries approx=True and the page draws it
hollow, because "the Japanese wire ran this" is not the same knowledge as "this
happened in Osaka".

Names come with the source data's alternate spellings, so a headline in
Russian, Arabic, Japanese or Chinese resolves as readily as one in English.

Generated by build_gazetteer.py. Do not hand-edit the table.
"""

import gzip
import json
import os
import re

_HERE = os.path.dirname(os.path.abspath(__file__))
_DATA = os.path.join(_HERE, "places.json.gz")

with gzip.open(_DATA, "rt", encoding="utf-8") as _fh:
    _RAW = json.load(_fh)

# term -> [label, lat, lon, rank]   rank 3 settlement, 2 division, 1 country
TABLE = _RAW["table"]
# ISO-2 of a Google News locale -> the point to fall back on
LOCALE = _RAW["locale"]
# an institution's name -> the ISO-2 it belongs to
INSTITUTIONS = _RAW["institutions"]

_WORD = re.compile(r"\w", re.UNICODE)
_CJK = re.compile(r"[\u3040-\u30ff\u3400-\u9fff\uac00-\ud7af]")
_TOKEN = re.compile(r"[^\W\d_]+", re.UNICODE)


_INFLECTED = re.compile(r"[\u0370-\u03ff\u0400-\u04ff]")   # Greek, Cyrillic
_INFLECT_MAX = 3          # "Новосибирск" + "е", "Украин" + "ою"


def _edges(text, term, start):
    """Word-boundary test, adapted to the scripts the fleet actually reads.

    Chinese and Japanese are written without word breaks, so a boundary test
    would reject every correct match; for those terms position alone is the
    test. Greek and Russian inflect the place name itself — a story says "в
    Новосибирске", not "в Новосибирск" — so a short trailing ending is allowed
    there. Everywhere else the character on either side must not be a word
    character, or "mali" matches inside "Somalia"."""
    if _CJK.search(term):
        return True
    if start > 0 and _WORD.match(text[start - 1]) and _WORD.match(term[0]):
        return False
    end = start + len(term)
    if end >= len(text) or not _WORD.match(text[end]):
        return True
    if not _INFLECTED.search(term):
        return False
    tail = 0
    while end + tail < len(text) and _WORD.match(text[end + tail]):
        tail += 1
        if tail > _INFLECT_MAX:
            return False
    return True


def _find(text, term):
    i = text.find(term)
    while i >= 0:
        if _edges(text, term, i):
            return i
        i = text.find(term, i + 1)
    return -1


# --------------------------------------------------------------------------
# Index. Scanning sixty-odd thousand terms against every headline is far too
# slow for a harvest, so terms are filed under their first word and only the
# words a headline actually contains are ever looked up. Terms in scripts with
# no word breaks cannot be indexed that way and are scanned directly, but there
# are few enough of those for it not to matter.
# --------------------------------------------------------------------------
_BY_FIRST = {}
_SCAN = []

for _term, _entry in TABLE.items():
    if _CJK.search(_term):
        _SCAN.append((_term, _entry))
        continue
    _head = _TOKEN.search(_term)
    if not _head:
        _SCAN.append((_term, _entry))
        continue
    _BY_FIRST.setdefault(_head.group(0), []).append((_term, _entry))

# longest first inside each bucket, so "south sudan" is tested before "sudan"
for _k in _BY_FIRST:
    _BY_FIRST[_k].sort(key=lambda kv: -len(kv[0]))
_SCAN.sort(key=lambda kv: -len(kv[0]))


def resolve(text, locale=None):
    """Where the story is.

    Returns (label, [lat, lon], approx). approx is True only when nothing in
    the text placed it and the point came from the reporting locale.
    """
    low = text.lower()

    best = None      # (rank, -position, label, lat, lon)

    def offer(term, entry, pos):
        nonlocal best
        label, lat, lon, rank = entry
        cand = (rank, -pos, label, lat, lon)
        if best is None or cand > best:
            best = cand

    for m in _TOKEN.finditer(low):
        word = m.group(0)
        bucket = _BY_FIRST.get(word)
        if bucket is None and _INFLECTED.search(word):
            # the name itself carries the case ending, so the token in the text
            # is longer than the term filed in the index
            for cut in range(1, _INFLECT_MAX + 1):
                if len(word) - cut < 4:
                    break
                bucket = _BY_FIRST.get(word[:-cut])
                if bucket:
                    break
        if not bucket:
            continue
        for term, entry in bucket:
            if low.startswith(term, m.start()) and _edges(low, term, m.start()):
                offer(term, entry, m.start())
                break          # longest match at this position wins

    if _CJK.search(low):
        for term, entry in _SCAN:
            pos = _find(low, term)
            if pos >= 0:
                offer(term, entry, pos)
                if entry[3] == 3:
                    break

    if best:
        return best[2], [best[3], best[4]], False

    for name, iso in INSTITUTIONS.items():
        if _find(low, name) >= 0 and iso in LOCALE:
            pt = LOCALE[iso]
            return pt[0], [pt[1], pt[2]], False

    if locale:
        pt = LOCALE.get(locale.upper())
        if pt:
            return pt[0], [pt[1], pt[2]], True

    return None, None, False


def resolve_ranked(text, locale=None):
    """As resolve(), but also returns how specific the answer is:
    3 a settlement, 2 a division, 1 a country, 0 the reporting locale."""
    low = text.lower()
    best = None
    for m in _TOKEN.finditer(low):
        word = m.group(0)
        bucket = _BY_FIRST.get(word)
        if bucket is None and _INFLECTED.search(word):
            for cut in range(1, _INFLECT_MAX + 1):
                if len(word) - cut < 4:
                    break
                bucket = _BY_FIRST.get(word[:-cut])
                if bucket:
                    break
        if not bucket:
            continue
        for term, entry in bucket:
            if low.startswith(term, m.start()) and _edges(low, term, m.start()):
                cand = (entry[3], -m.start(), entry[0], entry[1], entry[2])
                if best is None or cand > best:
                    best = cand
                break
    if _CJK.search(low):
        for term, entry in _SCAN:
            pos = _find(low, term)
            if pos >= 0:
                cand = (entry[3], -pos, entry[0], entry[1], entry[2])
                if best is None or cand > best:
                    best = cand
                if entry[3] == 3:
                    break
    if best:
        return best[2], [best[3], best[4]], best[0], False
    for name, iso in INSTITUTIONS.items():
        if _find(low, name) >= 0 and iso in LOCALE:
            pt = LOCALE[iso]
            return pt[0], [pt[1], pt[2]], 1, False
    if locale:
        pt = LOCALE.get(locale.upper())
        if pt:
            return pt[0], [pt[1], pt[2]], 0, True
    return None, None, -1, False


def resolve_point(text, locale=None):
    """The two-value form the harvesters' point_for() already returns."""
    label, point, _approx = resolve(text, locale)
    return label, point
